CREATE DATABASE wedding;

CREATE TABLE guest (id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL, email VARCHAR(255), phone VARCHAR(15), confirmed BOOLEAN, confirmed_date TIMESTAMP DEFAULT NOW());

CREATE USER 'app'@'localhost' IDENTIFIED BY PASSWORD '*9785F0319567EA2790E1D2B870363A46E2A883D5';

GRANT SELECT, INSERT, UPDATE ON wedding.* TO 'app'@'localhost';

CREATE TABLE message (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(255),
  message VARCHAR(1024),
  submit_date TIMESTAMP DEFAULT NOW(),
  visible BOOLEAN
);

CREATE TABLE badword (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  badword VARCHAR(100) NOT NULL
);